apiVersion: iter8.tools/v1alpha1
kind: Experiment 
metadata:
  name: reviews
  labels:
    app.kubernetes.io/name: reviews
spec:
  targetService:
    name: reviews
    apiVersion: v1 
    baseline: reviews-v1
    candidate: reviews-v2
  trafficControl:
    strategy: check_and_increment
    interval: 30s
    trafficStepSize: 10
    maxIterations: 9
    maxTrafficPercentage: 90
  analysis:
    analyticsService: "http://iter8-analytics.iter8"
    successCriteria:
      - metricName: iter8_latency
        toleranceType: threshold
        tolerance: 0.2
        sampleSize: 5
